#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

use App\Core\Helpers;

use Symfony\Component\Console\Application;

// Bootstrap your app: database, services, etc.
// (If you have AppServiceProvider or similar, call it here)
App\Config\Database::init();

$application = new Application('MyBackend CLI', Helpers::config('app.version', 'dev'));

$dir = __DIR__.'/app/Console';
$files = glob($dir.'/*.php');

foreach ($files as $file) {
    require_once $file;

    $class = 'App\\Console\\'.basename($file, '.php');

    $ref = new \ReflectionClass($class);
    $attribs = $ref->getAttributes(\Symfony\Component\Console\Attribute\AsCommand::class);

    if (!empty($attribs)) {
        $application->addCommand($ref->newInstance());
    }
}

$application->run();