name: Build Images

env:
  FORGEJO_REGISTRY: ${{ vars.FORGEJO_DOMAIN }}

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: linux-amd64
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
      volumes:
        - /etc/ssl/certs:/etc/ssl/certs:ro
        - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
        - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORGEJO_TOKEN }}

      - name: Set variables
        run: |
          echo "TAG=git-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "FORGEJO_IMAGE=${GITHUB_REPOSITORY}" >> $GITHUB_ENV

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."git.dariussg.intra"]
              ca=["/etc/ssl/certs/ca-certificates.crt"]

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.FORGEJO_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build & Push (Bake)
        uses: docker/build-push-action@v7
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          files: docker-bake.hcl
          targets: default
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            FORGEJO_REGISTRY=${{ env.FORGEJO_REGISTRY }}
            FORGEJO_IMAGE=${{ env.FORGEJO_IMAGE }}
            TAG=${{ env.TAG }}